#! /usr/bin/env python

PROJECT = "TaskTray"
SITE = "rox4debian.berlios.de"

import findrox; findrox.version(1, 9, 6)
import rox, os

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

import sys
sys.path.append(os.path.dirname(__file__))
sys.path.append(os.path.join(os.path.dirname(__file__), 'TrayLib'))
from tasktray.main import TaskTrayMain

rox.setup_app_options(PROJECT, 'Options.xml', SITE)

TaskTrayMain().mainloop(sys.argv)
