#! /usr/bin/env python3

PROJECT = "TaskTray"
SITE = "dtomas"

import sys, os
sys.path.append(os.path.dirname(__file__))
sys.path.append(os.path.join(os.path.dirname(__file__), 'TrayLib'))
sys.path.append(
    os.path.join(os.path.dirname(__file__), 'rox-lib', 'ROX-Lib3', 'python')
)

import rox
from tasktray.main import TaskTrayMain

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

rox.setup_app_options(PROJECT, 'Options.xml', SITE)

TaskTrayMain().mainloop(sys.argv)
